version: '3.9'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: codemotion
      POSTGRES_USER: codemotion
      POSTGRES_DB: codemotion
    volumes:
      - ./db-data:/var/lib/postgresql/data
  api:
    image: codemotion/docker-api
    build: ./server
    restart: always
    environment:
      DB_CONN: 'host=db user=codemotion password=codemotion dbname=codemotion port=5432 sslmode=disable'
    ports:
      - 8080:8080
    depends_on:
      - db
  gui:
    image: codemotion/docker-gui
    build: ./client
    restart: always
    ports:
      - 8081:80
